- name: HCP
  hosts: all
  tasks:
  - name: Create a new Terraform run with auto-apply
    hashicorp.terraform.run:
      workspace: "tf-random-pet"
      organization: "TechXchangeNL"
      run_message: "Deploy new application version"
      auto_apply: true
      variables:
        - key: "environment"
          value: "production"
        - key: "app_version"
          value: "v1.2.3"
      state: "present"
